/**
 * Legal copy sourced from BestBond Terms & Privacy PDF (May 2026).
 * Update this file when legal publishes a new version.
 */
export const LEGAL_UPDATED_ON = '9 May 2026';

export const TERMS_AND_CONDITIONS_TITLE = 'Terms & Conditions';

export const PRIVACY_POLICY_TITLE = 'Privacy Policy';

export const TERMS_AND_CONDITIONS_BODY = `TERMS & CONDITIONS 
BestBond Rewards Program Mobile Application 
Last Updated: May 2026 
Welcome to the BestBond Rewards Program (“Program”) operated by BestBond. The 
Program is designed for contractors, painters, dealers, and other eligible channel partners to 
earn and redeem reward points through QR-based coupon scanning and reward activities.  
By registering, accessing, or using the Application, you agree to these Terms & Conditions. 
 
1. DEFINITIONS 
• Company / BestBond / We / Our / Us refers to BestBond and its authorized 
representatives.  
• Application means the BestBond Rewards mobile application and admin 
management system.  
• User means contractors, painters, dealers, applicators, or approved participants 
enrolled in the Program.  
• Coupon means a unique QR-enabled reward code generated by the Company.  
• Points means reward points credited to a user’s wallet after successful coupon 
validation.  
• Wallet means the in-app digital rewards balance available to eligible users.  
• Redemption means conversion of accumulated reward points into approved gifts, 
benefits, or rewards.  
 
2. ELIGIBILITY 
The Program is available only to: 
• Registered contractors  
• Painters  
• Applicators  
• Dealers  
• Authorized channel partners approved by BestBond  
To participate: 
• Users must provide valid mobile numbers and accurate registration details.  
• Users must be at least 18 years old.  
• Users may be required to submit identity proof or dealer verification documents.  
BestBond reserves the right to approve, reject, suspend, or terminate any account without 
prior notice. 
 
3. USER REGISTRATION & ACCOUNT RESPONSIBILITY 
Users are responsible for: 
• Maintaining accurate profile information  
• Protecting login credentials and OTP access  
• Ensuring that only they access their account  
The Company shall not be liable for: 
• Unauthorized account access due to negligence  
• Mobile number misuse  
• Loss of rewards caused by incorrect information submitted by users  
Multiple fake or duplicate accounts may lead to immediate account suspension. 
 
4. QR COUPON SYSTEM 
The Program operates on a QR-based coupon system similar to modern contractor reward 
programs used within the construction materials industry.  
4.1 Coupon Structure 
Each coupon contains: 
• Unique coupon identification number  
• QR code  
• Assigned reward value  
• Product or campaign mapping  
4.2 Coupon Usage Rules 
• Coupons are valid for one-time use only.  
• Once scanned successfully, the coupon becomes permanently inactive.  
• Duplicate, damaged, expired, manipulated, or unauthorized coupons will be rejected 
automatically.  
4.3 Coupon Validation Flow 
1. User scans QR code using the Application.  
2. System validates coupon authenticity.  
3. Reward points are credited to the wallet.  
4. Coupon becomes inactive after successful usage.  
4.4 Fraud Prevention 
The following are strictly prohibited: 
• Duplicate scans  
• Fake QR generation  
• Coupon resale  
• Unauthorized coupon distribution  
• Manipulation of the reward system  
BestBond reserves the right to: 
• Reverse points  
• Block accounts  
• Reject redemption requests  
• Initiate legal proceedings in case of fraud or abuse  
 
5. REWARD WALLET 
• Successfully validated coupons will add points to the user wallet instantly or within a 
reasonable processing period.  
• Points have no direct cash value unless specifically permitted by the Company.  
• Wallet balances are non-transferable.  
• Users cannot sell, exchange, or transfer reward points to other users.  
The Company reserves the right to: 
• Modify point structures  
• Revise campaign benefits  
• Introduce validity periods or expiry dates  
• Update earning rules without prior notice  
 
6. REDEMPTION POLICY 
6.1 Worker Redemption (Slab-Based) 
Workers may redeem points only through predefined redemption slabs. 
Illustrative slabs may include: 
• 5,000 points  
• 10,000 points  
• 25,000 points  
BestBond may modify slabs periodically. 
6.2 Redemption Process 
1. User selects the redemption option.  
2. User chooses an eligible slab.  
3. Redemption request is submitted for review.  
4. Admin reviews and approves/rejects the request.  
5. Gift or benefit is processed for dispatch.  
Users may receive messages such as: 
“Your gift is on the way.” 
6.3 Redemption Approval 
All redemptions are subject to: 
• Internal verification  
• Stock availability  
• Fraud checks  
• Eligibility validation  
BestBond reserves the right to reject redemption requests if suspicious activity is detected. 
6.4 Gift Dispatch & Delivery 
• Rewards may include merchandise, vouchers, electronics, appliances, tools, or 
promotional benefits.  
• Delivery timelines are indicative and may vary.  
• BestBond shall not be liable for delays caused by logistics providers or force majeure 
events.  
6.5 Dealer Redemption 
Dealers may not directly redeem rewards through the standard worker redemption process. 
Dealer rewards, if applicable, may be processed only through: 
• Authorized company personnel  
• Sales representatives  
• Approved operational channels  
 
7. ACCOUNT DASHBOARD & TRANSACTION HISTORY 
Users may access: 
• Current wallet balance  
• Coupon scan history  
• Redemption history  
• Redemption status  
• Reward transaction statements  
• Support contact details  
Transaction history shown in the Application shall be considered final unless proven 
otherwise. 
 
8. ADMIN MANAGEMENT SYSTEM 
The Program includes a role-based admin application. 
8.1 Super Admin 
Super Admins may: 
• Generate coupons  
• Access analytics dashboards  
• Approve or reject redemptions  
• Manage users  
• Monitor platform-wide activities  
8.2 Operational Admin 
Operational Admins may: 
• Process redemptions  
• Coordinate reward dispatch  
• Assist customers  
• Manage operational workflows  
All admin activities may be logged for audit and security purposes. 
 
9. ANALYTICS & BUSINESS INSIGHTS 
The platform may generate centralized analytics including: 
• Coupons generated  
• Coupons scanned  
• Points issued  
• Redemption trends  
• Active user reports  
• Product engagement data  
These analytics help BestBond improve operations, reward programs, and channel 
engagement strategies. 
 
10. INTELLECTUAL PROPERTY 
All application components including: 
• Logos  
• Branding  
• QR systems  
• Software  
• Reward mechanisms  
• Databases  
• UI/UX designs  
are the exclusive intellectual property of BestBond and may not be copied, reproduced, or 
distributed without written authorization. 
 
11. THIRD-PARTY SERVICES 
The Application may integrate with: 
• SMS gateways  
• Push notification systems  
• Cloud hosting providers  
• Analytics providers  
• Delivery partners  
BestBond is not responsible for service interruptions caused by third-party providers. 
 
12. LIMITATION OF LIABILITY 
BestBond shall not be liable for: 
• Temporary application downtime  
• Server interruptions  
• Internet/network issues  
• Failed scans caused by damaged QR codes  
• Delayed gift dispatch  
• Unauthorized account usage resulting from user negligence  
The Application is provided on an “as available” and “as is” basis. 
 
13. TERMINATION & SUSPENSION 
BestBond reserves the right to: 
• Suspend or terminate accounts  
• Cancel points  
• Reject redemption requests  
• Block access to the Program  
if users violate these Terms or misuse the platform. 
 
14. MODIFICATIONS TO THE PROGRAM 
BestBond may: 
• Modify these Terms  
• Update reward structures  
• Change redemption rules  
• Introduce or discontinue campaigns  
• Alter point values  
without prior notice. 
Continued usage of the Application constitutes acceptance of updated Terms. 
 
15. GOVERNING LAW & JURISDICTION 
These Terms shall be governed by the laws of India. 
Any disputes arising from the Program shall fall under the jurisdiction of competent courts in 
Karnataka, India.`;

export const PRIVACY_POLICY_BODY = `PRIVACY POLICY 
BestBond Rewards Program Mobile Application 
Last Updated: May 2026 
BestBond is committed to protecting the privacy and personal information of users 
participating in the BestBond Rewards Program. 
This Privacy Policy explains how information is collected, used, stored, and protected. 
 
1. INFORMATION WE COLLECT 
1.1 Personal Information 
We may collect: 
• Full name  
• Mobile number  
• Email address  
• Address information  
• Dealer/contractor identification details  
• Profile photographs (if applicable)  
• Bank or payout details (if applicable)  
1.2 Reward Program Information 
We may collect: 
• QR scan activity  
• Coupon usage history  
• Wallet balance  
• Redemption requests  
• Reward preferences  
• Transaction history  
1.3 Technical Information 
The Application may automatically collect: 
• Device type  
• Operating system  
• IP address  
• App version  
• Device identifiers  
• Network information  
• Crash reports and diagnostics  
 
2. HOW WE USE INFORMATION 
We use collected information to: 
• Register and manage user accounts  
• Validate QR coupon scans  
• Credit reward points  
• Process redemption requests  
• Deliver gifts and rewards  
• Provide customer support  
• Improve platform functionality  
• Prevent fraud and abuse  
• Conduct analytics and reporting  
• Communicate promotional campaigns and updates  
The Program follows a structured QR-driven contractor engagement model commonly used 
within the construction materials industry.  
 
3. CAMERA, STORAGE & DEVICE PERMISSIONS 
The Application may request access to: 
• Camera – to scan QR codes  
• Storage – to upload documents or store temporary files  
• Notifications – to provide reward and redemption updates  
• Location (optional) – to improve service availability and campaign relevance  
Permissions are used solely for operational functionality. 
 
4. COUPON & TRANSACTION SECURITY 
Every QR coupon: 
• Is uniquely generated  
• Can be used only once  
• Is validated against the central server  
All transactions are securely logged to: 
• Prevent misuse  
• Enable audits  
• Resolve disputes  
• Maintain redemption accuracy  
 
5. INFORMATION SHARING 
We do not sell personal information. 
Information may be shared with: 
• Authorized operational teams  
• Delivery/logistics partners  
• Cloud hosting providers  
• SMS and communication providers  
• Legal or regulatory authorities where required by law  
All such parties are expected to maintain appropriate confidentiality standards. 
 
6. DATA RETENTION 
User data may be retained: 
• For operational requirements  
• For redemption history and accounting purposes  
• For fraud prevention and legal compliance  
• For audit and reporting needs  
The Company may retain certain records even after account deactivation where legally 
required. 
 
7. DATA SECURITY 
We implement reasonable security measures including: 
• Secure server infrastructure  
• Encrypted communication protocols  
• Role-based access control  
• Authentication systems  
• Monitoring and audit logs  
However, no digital system can guarantee absolute security. 
 
8. USER RIGHTS 
Users may request: 
• Access to their information  
• Correction of inaccurate data  
• Account deactivation  
• Assistance regarding transaction disputes  
Requests may be submitted through the support details provided within the Application. 
 
9. THIRD-PARTY SERVICES 
The Application may contain integrations with third-party services including: 
• Cloud infrastructure providers  
• Analytics services  
• Push notification providers  
• SMS gateways  
• Customer support tools  
Such services may operate under their own privacy policies. 
 
10. CHILDREN’S PRIVACY 
The Program is intended only for users above 18 years of age. 
We do not knowingly collect information from minors. 
 
11. CHANGES TO THIS PRIVACY POLICY 
BestBond reserves the right to update this Privacy Policy periodically. 
Updated versions shall be published within the Application and/or official communication 
channels.`;
